if(EXISTS ${PROJECT_SOURCE_DIR}/enki/CMakeLists.txt)
	add_subdirectory(${PROJECT_SOURCE_DIR}/enki)
	message("Using Enki from ${PROJECT_SOURCE_DIR}/enki")
else()
	find_package(enki REQUIRED)
	add_library(enki INTERFACE)
	target_include_directories(enki INTERFACE ${enki_INCLUDE_DIR})
	target_link_libraries(enki INTERFACE ${enki_LIBRARY})
	add_library(enki_viewer INTERFACE)
	target_include_directories(enki_viewer INTERFACE ${enki_INCLUDE_DIR})
	target_link_libraries(enki_viewer INTERFACE ${enki_VIEWER_LIBRARY} enki Qt5::OpenGL Qt5::Widgets Qt5::Gui Qt5::Core)
endif()
