if(EXISTS ${PROJECT_SOURCE_DIR}/enki/CMakeLists.txt)
	add_subdirectory(${PROJECT_SOURCE_DIR}/enki)
	message("Using Enki from ${PROJECT_SOURCE_DIR}/enki")
else()
	find_package(enki REQUIRED)
	add_library(enki INTERFACE)
	target_include_directories(enki INTERFACE ${enki_INCLUDE_DIR})
	target_link_libraries(enki INTERFACE ${enki_LIBRARY})

	find_package(Qt5Widgets)
	find_package(Qt5OpenGL)
	find_package(OpenGL)

	if (Qt5Widgets_FOUND AND Qt5OpenGL_FOUND AND OPENGL_FOUND)
		add_library(enki_viewer INTERFACE)
		target_include_directories(enki_viewer INTERFACE ${enki_INCLUDE_DIR} ${OPENGL_INCLUDE_DIRS})
		target_link_libraries(enki_viewer INTERFACE ${enki_VIEWER_LIBRARY} enki Qt5::OpenGL Qt5::Widgets Qt5::Gui Qt5::Core ${OPENGL_LIBRARIES})
	endif()

endif()
